# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0016_userstory_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='is this important'),
        ),
    ]
